---
# ansible_playbook_infra_freeipa/collections/requirements.yml
# Author: MTO
# Description: Collections requirements.yml for freeipa
#
 collections:
  - name: freeipa.ansible_freeipa
    version: 0.3.5
    source: https://galaxy.ansible.com

